install.packages("stats")
install.packages("dplyr")
install.packages("randomForest")
install.packages("caTools")
library(stats)
library(dplyr)
library(randomForest)
library(caTools)
x<-read.csv("C:\\Users\\WAL 68\\Desktop\\data.csv")
data<-x[c(1:768),-c(11,12)]
si = sample.split(data,SplitRatio=0.7)
tr=subset(data,S1=TRUE)
ts=subset(data,S1=FALSE)
set.seed(120)
model=randomForest(x=tr[-9],y=tr$Y1,ntree=500,na.action=na.omit)
y1_predict=predict(model,ts[-9])
conmet=table(ts[,5],y1_predict)
plot(model)
importance(model)
varImpPlot(model)
conmet=table(ts[,5],y1_predict)
plot(model)
importance(model)
